const ActionTypes = {
  REST_LOADING: "REST_LOADING",
  REST_SUCCESS: "REST_SUCCESS",
  REST_ERROR: "REST_ERROR",

  PROD_LOADING: "PROD_LOADING",
  PROD_SUCCESS: "PROD_SUCCESS",
  PROD_ERROR: "PROD_ERROR",

  CART_LOADING: "CART_LOADING",
  CART_SUCCESS: "CART_SUCCESS",
  CART_ERROR: "CART_ERROR",
  AD_TO_CART: "AD_TO_CART",
  ADD_ITEM: "ADD_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
  UPDATE_ITEM: "UPDATE_ITEM",
};

export default ActionTypes;
